In [1]:
numbers=[ 1,25,10,45,58,95,36,56,74,21,22,88]

In [2]:
for number in numbers:
    if number%2==0:
        print(f"{number},Thats an even number.")
    elif number% 2 !=0:
        print("Thats an odd number.")

Thats an odd number.
Thats an odd number.
10,Thats an even number.
Thats an odd number.
58,Thats an even number.
Thats an odd number.
36,Thats an even number.
56,Thats an even number.
74,Thats an even number.
Thats an odd number.
22,Thats an even number.
88,Thats an even number.


## Functions

A function is a reusable set of instructions. A function takes one or more inputs, performs certain
operations, and often returns an output.

In [3]:
# def keyword is used to define a function.
# once defined, you need to call it or invoke it
def say_hello():
    print(" Hello, my girl.")

In [4]:
say_hello()

 Hello, my girl.



Functions can also accept one or more values as inputs (also knows as arguments or parameters).
Arguments help us write flexible functions which can perform the same operation on different
values. Further, functions can also return a value as a result using the return keyword, which
can be stored in a variable or used in other expressions.

In [5]:
def pick_even_numbers(numbers):
    result=[]
    for number in numbers:
        if number%2==0:
            result.append(number)
    return result

In [6]:
pick_even_numbers(numbers)

[10, 58, 36, 56, 74, 22, 88]

#Quiz

Radha is planning to buy a house that costs $1, 260,000 . She considering two
options to finance her purchase:

. Option 1: Make an immediate down payment of $300,000, and take loan 8-
year loan with an interest rate of 10% (compounded monthly) for the remaining
amount.
. Option 2: Take a 10-year loan with an interest rate of 8% (compounded
monthly) for the entire amount.

Both these loans have to paid back in equal monthly installments (EMIs). Which
loan has a lower EMI among the two?

In [7]:
def loan_emi(amount):
    emi= amount/12
    print(emi)

In [8]:
loan_emi(1260000)

105000.0


In [9]:
def loan_emi(amount, duration):
    emi= amount/duration
    print(emi)

In [10]:
loan_emi(1260000, 12)

105000.0


The variable emi defined inside the function is not accessible outside the function. The
same is true for the parameters amount and duration . These are all local variables that lie
within the scope of the function.

Scope: Scope refers to the region within the code where a certain variable is
visible. Every function (or class definition) defines a scope within Python. Variables
defined in this scope are called local variables. Variables that are available
everywhere are called global variables. Scope rules allow you to use the same
variable names in different functions without sharing values from one to the other.

## Comapreing the two options(Assuming there was no ineterest)

In [11]:
loan_emi(1260000,8*12)

13125.0


In [12]:
loan_emi(1260000,10*12)

10500.0


### Return values

As you might expect, the EMI for the 6-year loan is higher compared to the 10-year loan. Right
now we're printing out the result, but it would be better to return it and store the results in variables
for easier comparison. We can do this using the return statement

In [13]:
def loan_emi(amount, duration):
    emi= amount/duration
    return emi

In [14]:
emi1= loan_emi(1260000,8*12)

In [15]:
emi2= loan_emi(1260000,10*12)

In [16]:
emi1

13125.0

In [17]:
emi2

10500.0

In [18]:
# this is same as writing 300,000
3e5

300000.0

## Optional argumnents

Let's now add another argument to account for the immediate down payment. We'll make this an
optional argument, with a default value of 0.

In [19]:
def loan_emi(amount, duration, down_payment=0):
    loan_amount= amount- down_payment
    emi= loan_amount/duration
    return emi

In [20]:
Emi1= loan_emi(1260000,8*12,300000)
Emi1

10000.0

In [21]:
Emi2= loan_emi(1260000,10*12,0)
Emi2

10500.0

Next, let's add the interest calculation into the function. Here's the formula used to calculate th
EMI for a loan:

EMI = Pxrx (1+r)"
(1+r)"-1

where:

. P is the loan amount (principal)

. n is the no. of months

. r is the rate of interest per month

In [22]:
def loan_emi(amount, duration, rate, down_payment=0):
    loan_amount = amount - down_payment
    emi = loan_amount * rate * ((1+rate) ** duration) / (((1+rate) ** duration)-1)
    return emi

In [23]:
emi1= loan_emi(1260000, 8*12, 0.1/12,3e5)
emi1

14567.19753389219

In [24]:
emi2= loan_emi(1260000, 10*12, 0.08/12)
emi2

15287.276888775077

In [25]:
if emi1> emi2:
    print(" Option 1 has a lower emi.  ") 
else:
    print("Option 2 has a higher emi.")

Option 2 has a higher emi.


## QUIZ1

Exercise - Data Analysis for Vacation Planning
You're planning a leisure trip (vacation) and you need to decide which city you want to visit. You
have shortlisted 4 cities, and identified the cost of the return flight, daily hotel cost and a weekly
car rental cost (a car has to be rented for full weeks, even if you return the car before a week ends).

 City Return Flight ($)  Hotel per day ($)  Weekly Car Rental ( $)

 Paris    200                20                 200

 London   250                30                 120

 Dubai    370                15                 80

 Mumbai   450                10                 70


Answer the following questions using the data above:

1. If you're planning a 1-week long trip, which city should you visit to spend the least amount of
money?

2. How does the answer to the previous question change if you change the duration of the trip to
4 days, 10 days or 2 weeks?

3. If your total budget for the trip is $1000, which city should you visit to maximize the duration
of your trip? Which city should you visit if you want to minimize the duration?
                                             
4. How does the answer to the previous question change if your budget is $600, $2000 or
$1500 ?

Hint: To answer these questions, it will help to define a function cost_of_trip with relevant
inputs like flight cost, hotel rate, car rental rate and duration of the trip. You may find the
math.ceil function useful for calculating the total cost of car rental.




### NUMPY

In [26]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

# The three numbers in each vector represent the temperature, rainfall and humidity data respecively.
# The set of weights to be used in the forumla can also be represented as a vector.

weights = [w1, w2, w3]= 0.3,0.2,0.5

In [27]:
region= ['kanto','johto','hoenn','sinnoh','unova']

In [28]:
for x, y in zip(kanto,weights):
    x*y

In [29]:
def crop_yield(region, weights):
    result=0
    for x, y in zip(region,weights):
           result += x*y
    return result
    
    

In [30]:
crop_yield(kanto, weights)

56.8

In [31]:
crop_yield(johto, weights)

76.9

### Using numpy

In [32]:
import numpy as np

In [33]:
kanto = np.array([73, 67, 43])

In [34]:
kanto

array([73, 67, 43])

In [35]:
weights= np.array([w1, w2, w3])

In [36]:
weights

array([0.3, 0.2, 0.5])

In [37]:
type(weights)

numpy.ndarray

In [38]:
# arrays support indexing

kanto[1]

67

In [39]:
### Multi-dimensional Numpy arrays
# We can now go one step further, and represent the climate data for all the regions together using a
# single 2-dimensional Numpy array.

climate_data = np.array([ [73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

# The above 2-d array is a
# matrix with 5 rows (one for each region) and 3 columns (containing values for temperature, rainfall
# and humidity).

In [40]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [41]:
print(climate_data.shape)

(5, 3)


1D array- A single list of values, e.g. [1, 2, 3]

2D array- A list of lists (rows and columns), e.g. [[1,2,3],[4,5,6]]

In [42]:
# 3D array
arr3 = np.array([
   [[11, 12, 13],
   [13, 14, 15]],

   [[15, 16, 17],
   [17, 18, 19.5]]])


In [43]:
arr3.shape

(2, 2, 3)

In [44]:
arr3.dtype

dtype('float64')

In [45]:
climate_data.dtype

dtype('int32')

In [46]:
arr3

array([[[11. , 12. , 13. ],
        [13. , 14. , 15. ]],

       [[15. , 16. , 17. ],
        [17. , 18. , 19.5]]])

## numpy functions

## 1. Creating Arrays

- np.array()	Create an array from a list	i.e np.array([1,2,3])
- np.zeros()	Create an array filled with zerosi.e np.zeros((3,3))
- np.ones()	Create an array filled with ones i.e np.ones((2,4))
- np.full()	Create array with a constant value i.e np.full((3,3), 7)
- np.eye()	Identity matrix i.e	np.eye(3)
- np.arange()	Sequence of numbers	i.e np.arange(0,10,2)
- np.linspace()	Evenly spaced numbers i.enp.linspace(0,1,5)
- np.random.rand()	Random floats in [0,1) i.enp.random.rand(3,2)
- np.random.randint()	Random integers	 i.e np.random.randint(0,10,(3,3))

### 2. Inspecting Arrays

- .ndim	Number of dimensions i.e a.ndim
- .shape	Shape (rows, cols) i.e a.shape
- .size	Total number of elements i.e a.size
- .dtype	Data type i.ea.dtype

### 3. Mathematical Operations

These work element-wise by default.


- np.add(a,b) or a + b	Addition i.e np.add(a,b)
- np.subtract(a,b) or a - b	Subtraction	i.e np.subtract(a,b)
- np.multiply(a,b) or a * b	Multiplication i.e np.multiply(a,b)
- np.divide(a,b) or a / b	Division i.e np.divide(a,b)
- np.power(a,2)	Raise to a power i.e np.power(a,2)
- np.sqrt(a)	Square root	i.e np.sqrt(a)
- np.exp(a)	Exponential	i.e np.exp(a)
- np.log(a)	Natural log	i.e np.log(a)

### 4. Statistical Functions
- np.mean(a)	Average	i.e np.mean(a)
- np.median(a)	Median	i.e np.median(a)
- np.std(a)	Standard deviation	i.e np.std(a)
- np.var(a)	Variance	i.e np.var(a)
- np.min(a)	Minimum value	i.e np.min(a)
- np.max(a)	Maximum value	i.e np.max(a)
- np.sum(a)	Sum of all elements	i.e np.sum(a)
- np.argmin(a)	Index of min value	i.e np.argmin(a)
- np.argmax(a)	Index of max value	i.e np.argmax(a)

### 5. Array Manipulation

- np.reshape(a, (rows, cols))	Change shape	i.e np.reshape(a, (3,5))
- np.transpose(a) or a.T	Transpose (swap rows/cols)	i.e a.T
- np.concatenate([a,b], axis=0)	Stack arrays	i.e np.concatenate([...])
- np.vstack((a,b))	Stack vertically	i.e np.vstack((a,b))
- np.hstack((a,b))	Stack horizontally	i.e np.hstack((a,b))
- np.flatten()	Convert to 1D	i.e a.flatten()

### 6. Indexing & Filtering

- a[0,1]	Element at row 0, col 1	 i.e a[0,1]
- a[:, 1]	All rows, 2nd column	i.e a[:,1]
- a[a > 50]	Filter elements	i.e a[a > 50]
- np.where(a > 50)	Indices where condition true	i.e np.where(a > 50)

### 7. Linear Algebra (Bonus)

- np.dot(a,b)	Matrix multiplication	i.e np.dot(a,b)
- np.matmul(a,b)	Matrix multiplication (modern)	i.e np.matmul(a,b)
- np.linalg.inv(a)	Inverse of a matrix	i.e np.linalg.inv(a)
- np.linalg.det(a)	Determinant	i.e np.linalg.det(a)
- np.linalg.eig(a)	Eigenvalues/vectors	i.e np.linalg.eig(a)

### different operations

In [51]:
arr3= np.array( [ [11, 12, 13, 14],
[15, 16, 17, 18],
[19, 11, 12, 13]])

In [52]:
arr2= np.array([[1,2,3,4],
               [5,6,7,8],
               [9,1,2,3]])

In [53]:
arr3+arr2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

In [54]:
# adda a scalar
arr3+4

array([[15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 15, 16, 17]])

In [55]:
# element wise subtraction
arr3-arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [56]:
# division by scaler
arr3/2

array([[5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. ],
       [9.5, 5.5, 6. , 6.5]])

In [57]:
np.max(arr3)

19

In [58]:
# element-wise multiplication
arr3*arr2

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [59]:
# modulus
arr2%3

array([[1, 2, 0, 1],
       [2, 0, 1, 2],
       [0, 1, 2, 0]], dtype=int32)

## Broadcasting

In [60]:
# broadcasting
# allows arithmetics operations btn two matrices with different shapes
arr2.shape

(3, 4)

In [61]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [62]:
arr4= np.array([4,5,6,7])

In [63]:
arr4.shape

(4,)

In [64]:
arr2+arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

When the expression arr2 + arr4 is evaluated, arr4 (which has the shape (4,) ) is
replicated 3 times to match the shape (3, 4) of arr2 . This is pretty useful, because numpy
performs the replication without actually creating 3 copies of the smaller dimension array.

#### Broadcasting only works if one of the arrays can be replicated to exactly match the shape of the
other array.

In [65]:
arr5 = np.array([7, 8])

In [66]:
arr5.shape

(2,)

In [67]:
arr2 + arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

#### In the above example, even if arr5 is replicated 3 times, it will not match the shape of arr2,
hence arr2 + arr5 cannot be evaluted successfully.

In [68]:
arr1=np.array([[1,2,3],[3,4,5]])
arr2= np.array([[2,2,3],[1,2,5]])

In [69]:
arr1==arr2

array([[False,  True,  True],
       [False, False,  True]])

In [71]:
(arr1==arr2).dtype

dtype('bool')

In [73]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [74]:
arr1> arr2

array([[False, False, False],
       [ True,  True, False]])

A common use case for this is to count the number of equal elements in two arrays using the
sum method. Remember that True evalues to 1 and False evaluates to 0 when booleans
are used in arithmetic operations.

In [75]:
(arr1==arr2).sum()

3

### Indexing and Slicing

In [77]:
Arr3 = np.array ([
              [[11, 12, 13, 14],
                [13, 14, 15, 19]],

               [[15, 16, 17, 21],
               [63, 92, 36, 18]],

               [[98, 32, 81, 23],
               [17, 18, 19.5, 43]]])

In [78]:
Arr3.shape

(3, 2, 4)

In [80]:
Arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [81]:
Arr3[1,1]

array([63., 92., 36., 18.])

In [79]:
# single elemnts
Arr3[1,1,2]

36.0

In [83]:
Arr3

array([[[11. , 12. , 13. , 14. ],
        [13. , 14. , 15. , 19. ]],

       [[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

### Shape of the array

Arr3.shape → (3, 2, 4)

That means:

- 3 blocks (along axis 0),

- each block has 2 rows (axis 1),

- each row has 4 columns (axis 2).

In [85]:
# subarray using range
Arr3[1:]

#Indices along axis 0 are:
# 0 → first block
# 1 → second block
# 2 → third block


array([[[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

- Arr3[1:] keeps elements at indices 1 and 2.

In [87]:
Arr3[1:, 0:1]
#Then Axis 1 slice (0:1) keeps only the first row of each block:
# 0:1 → from index 0 up to (but not including) index 1 along axis 1 → keeps only the first row of each selected block, but keeps the dimension.

array([[[15., 16., 17., 21.]],

       [[98., 32., 81., 23.]]])

In [88]:
Arr3[1:, 0:1, :2]
#Take the first two columns (indices 0 and 1)

array([[[15., 16.]],

       [[98., 32.]]])

In [89]:
Arr3[1: ,1,3]

array([18., 43.])

In [90]:
## Step 1: 1: → take index 1 and 2 blocks:

[
 [[15., 16., 17., 21.],
  [63., 92., 36., 18.]],

 [[98., 32., 81., 23.],
  [17., 18., 19.5, 43.]]
]

[[[15.0, 16.0, 17.0, 21.0], [63.0, 92.0, 36.0, 18.0]],
 [[98.0, 32.0, 81.0, 23.0], [17.0, 18.0, 19.5, 43.0]]]

In [91]:
## Step 2: , 1, → take the 2nd row of each block:

[
 [63., 92., 36., 18.],
 [17., 18., 19.5, 43.]
]


[[63.0, 92.0, 36.0, 18.0], [17.0, 18.0, 19.5, 43.0]]

In [95]:
## Step 3: , 3 → take the 4th column (index 3):

#→ 18. from the first, 43. from the second.

#Final result
#Arr3([18., 43.])

### Other ways of creating arrays

In [96]:
# All zeros
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [97]:
# All ones
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

- np.ones() is a NumPy function that creates a new array filled entirely with 1s.

- The argument [2, 2, 3] tells NumPy what shape the array should have.
    
## [2, 2, 3] → means:

- 2 blocks (along axis 0)

- each block has 2 rows (axis 1)

- each row has 3 columns (axis 2)

In [98]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
# Random vector
# np.random.rand() is a NumPy random number generator that returns random numbers between 0 and 1 from a uniform distribution.
np.random.rand(5)

array([0.29827653, 0.85440178, 0.243163  , 0.48939766, 0.38905565])

In [100]:
 # Random matrix
# np.random.randn() generates random numbers from a standard normal (Gaussian) distribution, not from a uniform distribution.
np.random.randn(2, 3) # rand vs. randn - what's the difference?

array([[ 0.87221947, -0.23652336, -0.73779936],
       [-0.15046332,  2.22014147,  0.51672741]])

In [101]:
# fixed value
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [102]:
# using range with start, end and step
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [106]:
# equally spaced  numbers in a range
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])